### ISSUE TITLE
wikimedia/ip-set → mlocati/ip-lib

### ISSUE THREAD

**Issue by Diamochang** [zzyh1145/CN_DCMS-Social#8]
维基媒体基金会的 IP 工具均使用 GPL-2.0 授权，而这会导致版权冲突（GPL 要求所有使用在此协议授权下的库的程序**必须**使用 GPL 授权，而它的程序售卖相关内容与 DCMS 原有的协议冲突）。

建议使用 [mlocati/ip-lib](https://github.com/mlocati/ip-lib) 或其它通过 MIT（Expat） 协议授权的替代品，因为这个协议完全没有程序售卖相关内容，原有协议仍有不冲突的约束力。

**Comment by guguan123** [comment]
> 维基媒体基金会的 IP 工具均使用 GPL-2.0 授权，而这会导致版权冲突（GPL 要求所有使用在此协议授权下的库的程序**必须**使用 GPL 授权，而它的程序售卖相关内容与 DCMS 原有的协议冲突）。
> 
> 建议使用 [mlocati/ip-lib](https://github.com/mlocati/ip-lib) 或其它通过 MIT（Expat） 协议授权的替代品，因为这个协议完全没有程序售卖相关内容，原有协议仍有不冲突的约束力。

那时候已经注意到GPL的传染性问题了，但是实在没有时间去改了（好吧，其实是懒…）

**Comment by guguan123** [comment]
等什么时候有时间再改吧
